name: Build Android APK

on:
  push:
    branches:
      - main  # Cambia a la rama que uses

jobs:
  build:
    name: Build APK on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant permission to execute gradlew
        run: chmod +x ./android/gradlew

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
